### ISSUE TITLE
Can't publish with rabbitmq

### ISSUE THREAD

**Issue by dmathieu** [Leadformance/abstract-message-queue#1]
I'm using RabbitMQ on my dev machine.
Subscribing works well. But when I publish something, I get the following error :

```
=ERROR REPORT==== 20-Sep-2011::10:29:57 ===
STOMP error frame sent:
Message: "Processing error"
Detail: "Processing error\n"
Server private detail: {{{case_clause,
                          {badrpc,
                            {'EXIT',
                            {undef,
                             [{rabbit_direct,connect,
                               [<<>>,<<"/">>,rabbit_framing_amqp_0_9_1,
                                <0.16110.0>,
                                [{pid,<0.16110.0>},
                                 {protocol,{'STOMP',"1.0"}},
                                 {address,{0,0,0,0,0,0,0,1}},
                                 {port,61613},
                                 {name,unknown},
                                 {peer_address,{0,0,0,0,0,0,0,1}},
                                 {peer_port,55498},
                                 {user,<<>>},
                                 {vhost,<<"/">>},
                                 {client_properties,[]},
                                 {type,direct},
                                 {ssl,false}]]},
                              {rpc,local_call,3},
                              {amqp_direct_connection,connect,4},
                              {amqp_gen_connection,handle_call,3},
                              {gen_server,handle_msg,5},
                              {proc_lib,init_p_do_apply,3}]}}}},
                         [{amqp_direct_connection,connect,4},
                          {amqp_gen_connection,handle_call,3},
                          {gen_server,handle_msg,5},
                          {proc_lib,init_p_do_apply,3}]},
                        {gen_server,call,[<0.16110.0>,connect,infinity]}}
```

**Comment by dmathieu** [comment]
Apparently, this comes from stomp. I've added an integration test which demonstrated the problem. 4c7a16833101133bb4b745b07cad8a4a0250c30a

@whoward does this work on ActiveMQ ?

**Comment by whoward** [comment]
Yeah this whole gem was developed using ActiveMQ so it should still work.  

I briefly tested it with Stomp+RabbitMQ however and it appeared to work outside of another bug (publishing while a subscriber was disconnected did not deliver the message on the subscriber's reconnect).

Maybe RabbitMQ has had a regression? I ran this on RabbitMQ Server v2.5.1 (I think that's the version found in ubuntu's repositories).

I've also tested against ActiveMQ 5.5.0 - it seems to work very well

I've added examples/ which contain the examples from the readme - it doesn't seem to be working today on rabbitmq but maybe i'm missing some config.  I think there was some extra hoops to jump through to get that working.  They do work well on ActiveMQ.

An oddity with the integration test you've provided - it runs cleanly on "rake spec" but does not when you run "rspec spec/integration_test"

I also think it may be naturally failing because I believe this may be a non-blocking process, that'll be a hard thing to test.

I like the idea of having an integration test in here - but i think it should go into it's own suite, that way we can more easily run it against multiple backends with multiple combinations.

Comments?
